language: java
notifications:
  flowdock:
    secure: "bclwzoxJFeVSGQeC7TkTR2B7anIPnDZpXyVJbXkEjM/UxoO8D+ZQSStXXhABFrGQRgkTcGuGtaiJ0rFzRBRFZMokotHGL9SYwLsiscqBPEDFimED0x95PQVxxfoqhr9ww0MgIV12+GTKh/knl3oEd3pb0O/epOSBMQKaiVVBiBk="
